export const products = [
  {
    id: 1,
    name: "Minimalist Watch",
    description: "A sleek, minimalist watch with a leather strap. Perfect for any occasion.",
    price: 129.99,
    image: "/placeholder.svg?height=500&width=500",
    category: "accessories",
  },
  {
    id: 2,
    name: "Modern Desk Lamp",
    description: "An elegant desk lamp with adjustable brightness. Adds style to any workspace.",
    price: 79.99,
    image: "/placeholder.svg?height=500&width=500",
    category: "home",
  },
  {
    id: 3,
    name: "Wireless Earbuds",
    description: "High-quality wireless earbuds with noise cancellation and long battery life.",
    price: 149.99,
    image: "/placeholder.svg?height=500&width=500",
    category: "electronics",
  },
  {
    id: 4,
    name: "Ceramic Mug Set",
    description: "Set of 4 handcrafted ceramic mugs. Each piece is unique and made with care.",
    price: 49.99,
    image: "/placeholder.svg?height=500&width=500",
    category: "home",
  },
  {
    id: 5,
    name: "Canvas Backpack",
    description: "Durable canvas backpack with leather details. Spacious and stylish.",
    price: 89.99,
    image: "/placeholder.svg?height=500&width=500",
    category: "accessories",
  },
  {
    id: 6,
    name: "Portable Bluetooth Speaker",
    description: "Compact Bluetooth speaker with impressive sound quality and 12-hour battery life.",
    price: 69.99,
    image: "/placeholder.svg?height=500&width=500",
    category: "electronics",
  },
]
